import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const topicsData = {
  "Download Guides": [
    "How to Download YouTube Videos",
    "Save TikToks Without Watermark",
    "Instagram Reels Download Guide",
    "Twitter Video Downloader Tips",
    "Download Facebook Live Videos",
    "Save LinkedIn Video Posts",
    "Pinterest Video Download Steps",
    "Reddit Video Saver Guide",
    "Download Twitch Streams Easily",
    "Save Vimeo Private Videos",
    "Download Bilibili Videos Fast",
    "Save Rumble Videos Offline",
    "Download Snapchat Spotlight Videos",
    "Save WhatsApp Status Videos",
    "Download Telegram Video Files",
    "Save Dailymotion Videos Quick",
    "Download YouTube Shorts Easily",
    "Save Instagram Stories Anonymously",
    "Download Threads App Videos",
    "Save VKontakte (VK) Videos",
    "Download Odnoklassniki (OK) Videos",
    "Save Kick Streams Offline",
    "Download Periscope Archive Videos",
    "Save Flickr Video Files",
    "Download Tumblr Video Posts",
    "Save Imgur Video Clips",
    "Download 9GAG Video Memes",
    "Save iFunny Video Content",
    "Download Likee Videos Fast",
    "Save Kwai Videos Offline",
    "Download Triller Video Clips",
    "Save Mixcloud Audio/Video",
    "Download SoundCloud Tracks",
    "Save Bandcamp Audio Streams",
    "Download Mixcloud Sets",
    "Save Patreon Locked Videos",
    "Download OnlyFans Content Legally",
    "Save Discord Video Attachments",
    "Download Slack Video Messages",
    "Save Microsoft Teams Recordings",
    "Download Zoom Meeting Recordings",
    "Save Google Meet Captures",
    "Download Webex Session Videos",
    "Save Skype Video Calls",
    "Download Coursera Video Lectures",
    "Save Udemy Course Videos",
    "Download Skillshare Class Videos",
    "Save MasterClass Video Lessons",
    "Download edX Course Material",
    "Save Khan Academy Videos",
    "Download Ted Talks Offline",
    "Save PBS Documentaries",
    "Download BBC iPlayer Content",
    "Save CNN Video Clips",
    "Download Fox News Videos",
    "Save MSNBC News Segments",
    "Download ESPN Sports Highlights",
    "Save Sky Sports Clips",
    "Download NBA Recap Videos",
    "Save NFL Highlight Clips",
    "Download FIFA Match Replays",
    "Save UEFA Champions League Goals",
    "Download Formula 1 Highlights",
    "Save UFC Fight Clips",
    "Download WWE Match Highlights",
    "Save Olympics Video Archives",
    "Download Red Bull TV Videos",
    "Save GoPro Channel Videos",
    "Download DJI Drone Footage",
    "Save NASA Video Streams",
    "Download SpaceX Launch Videos",
    "Save Apple Event Keynotes",
    "Download Google I/O Videos",
    "Save WWDC Session Videos",
    "Download E3 Game Trailers",
    "Save IGN Game Reviews",
    "Download GameSpot Video Previews",
    "Save Polygon Gameplay Clips",
    "Download Kotaku Video Posts",
    "Save PC Gamer Hardware Reviews",
    "Download Linus Tech Tips",
    "Save MKBHD Video Reviews",
    "Download iJustine Tech Vlogs",
    "Save MrBeast Challenge Videos",
    "Download PewDiePie Gameplay",
    "Save Markiplier Horror Let's Plays",
    "Download Jacksepticeye Videos",
    "Save DanTDM Minecraft Videos",
    "Download Ninja Fortnite Streams",
    "Save Shroud Valorant Clips",
    "Download Pokimane Stream Highlights",
    "Save Valkyrae YouTube Streams",
    "Download xQc React Videos",
    "Save HasanAbi Political Streams",
    "Download Ludwig Challenge Videos",
    "Save MoistCr1TiKaL Commentary",
    "Download Asmongold MMO Streams",
    "Save Kai Cenat VODs",
    "Download IShowSpeed Crazy Moments",
    "Save Adin Ross Streams",
    "Download Logan Paul Podcasts",
    "Save Jake Paul Fight Promos",
    "Download KSI Music Videos",
    "Save Sidemen Sunday Episodes",
    "Download Dude Perfect Trick Shots",
    "Save Lofi Girl Streams",
    "Download ChilledCow Playlists",
    "Save Monstercat Music Streams",
    "Download NCS No Copyright Sounds",
    "Save Vevo Music Videos",
    "Download Billboard Top Hits",
    "Save MTV Unplugged Sessions",
    "Download NPR Tiny Desk Concerts",
    "Save KEXP Live Performances",
    "Download BBC Radio 1 Live Lounge",
    "Save Boiler Room DJ Sets",
    "Download Cercle Electronic Sets",
    "Save Tomorrowland Festival Sets",
    "Download Ultra Music Festival Streams",
    "Save EDC Las Vegas Sets",
    "Download Coachella Live Performances",
    "Save Lollapalooza Concert Videos",
    "Save Glastonbury Set Highlights",
    "Save Bonnaroo Festival Clips",
    "Download SXSW Panel Videos",
    "Save Sundance Film Trailers",
    "Download Cannes Red Carpet Videos",
    "Save Oscars Acceptance Speeches",
    "Download Grammys Performance Clips",
    "Save Emmys Award Moments",
    "Download Golden Globes Highlights",
    "Save Tony Awards Performances",
    "Download MTV VMA Moments",
    "Save BET Awards Performances",
    "Download Kids Choice Awards Slime",
    "Save Nickelodeon Cartoon Clips",
    "Download Cartoon Network Shows",
    "Save Disney Channel Promos",
    "Download Pixar Short Films",
    "Save DreamWorks Animation Clips",
    "Download Studio Ghibli Trailers",
    "Save Anime Opening Themes",
    "Download Crunchyroll Fight Scenes",
    "Save Funimation Anime Clips",
    "Download MyAnimeList Recommendations",
    "Save IGN Anime Reviews",
    "Download Anime News Network Interviews",
    "Save Comic-Con Panel Videos",
    "Download Marvel Movie Trailers",
    "Save DC Universe Promos",
    "Download Star Wars Teasers",
    "Save Star Trek Episode Clips",
    "Download Doctor Who Highlights",
    "Save BBC Earth Nature Clips",
    "Download National Geographic Docs",
    "Save Discovery Channel Specials",
    "Download History Channel Docs",
    "Save Animal Planet Videos",
    "Download Travel Channel Guides",
    "Save Food Network Recipes",
    "Download Tasty Recipe Videos",
    "Save Gordon Ramsay Cooking Clips",
    "Download Jamie Oliver Recipes",
    "Save Babish Culinary Universe",
    "Download Joshua Weissman Recipes",
    "Save Uncle Roger Reviews",
    "Download First We Feast Hot Ones",
    "Save Epic Meal Time Classics",
    "Download Bon Appetit Test Kitchen",
    "Save America's Test Kitchen Videos",
    "Download Architectural Digest Tours",
    "Save Vogue Beauty Secrets",
    "Download GQ 10 Essentials",
    "Save Vanity Fair Lie Detector",
    "Download Wired Autocomplete Interviews",
    "Save BuzzFeed Unsolved Episodes",
    "Download Try Guys Challenges",
    "Save Watcher Entertainment Videos",
    "Download Good Mythical Morning",
    "Save Smosh Comedy Sketches",
    "Download CollegeHumor Originals",
    "Save SNL Weekly Sketches",
    "Download Key & Peele Classics",
    "Save Chappelle's Show Clips",
    "Download Netflix Standup Specials",
    "Save Comedy Central Roasts",
    "Download Late Night Show Monologues",
    "Save Jimmy Fallon Games",
    "Download Stephen Colbert Interviews",
    "Save Jimmy Kimmel Mean Tweets",
    "Download Conan O'Brien Remotes",
    "Save Seth Meyers Closer Looks",
    "Download James Corden Carpool Karaoke",
    "Save Trevor Noah Daily Show Clips",
    "Download John Oliver Main Stories",
    "Save Bill Maher New Rules",
    "Download Joe Rogan Podcast Clips",
    "Save Lex Fridman Interviews",
    "Download Andrew Huberman Labs",
    "Save Diary of a CEO Podcasts"
  ],
  "Content Strategies": [
    "Turn YouTube Videos Into Podcasts",
    "Convert Twitch Streams to TikToks",
    "Repurpose Webinars for YouTube",
    "Make Instagram Reels from YouTube",
    "Extract Audio for Spotify Podcasts",
    "Turn Zoom Calls Into Course Modules",
    "Create Pinterest Pins from Videos",
    "Repurpose Live Streams for IGTV",
    "Turn Long Videos into Twitter Threads",
    "Extract Quotes from Video Interviews",
    "Create GIFs from YouTube Videos",
    "Make LinkedIn Slides from Videos",
    "Repurpose TikToks for YouTube Shorts",
    "Turn Vlogs into Blog Posts",
    "Create Audiograms from Video Clips",
    "Repurpose Facebook Lives to YouTube",
    "Turn Tutorials into PDF Guides",
    "Make Meme Templates from Videos",
    "Repurpose IG Lives for Facebook",
    "Turn Snapchat Stories into Reels",
    "Extract B-Roll for Stock Footage",
    "Create Teaser Trailers for Courses",
    "Repurpose Product Demos for Sales",
    "Turn Customer Reviews into Video Ads",
    "Make Compilation Videos for YouTube",
    "Repurpose Behind-the-Scenes Footage",
    "Turn Q&A Sessions into FAQs",
    "Create Email Campaigns from Videos",
    "Repurpose Keynotes for Social Media",
    "Turn Event Footage into Promos",
    "Make Highlight Reels for Portfolios",
    "Repurpose Case Studies into Videos",
    "Turn Podcast Episodes into YouTube Videos",
    "Create Micro-Learning Clips",
    "Repurpose Old Videos for Throwbacks",
    "Turn Presentations into Video Courses",
    "Make Promo Videos from Old Content",
    "Repurpose Unboxing Videos for Ads",
    "Turn Gameplay Streams into Tutorials",
    "Create Reaction Videos from Clips",
    "Repurpose Interviews for Press Releases",
    "Turn Speeches into Motivational Clips",
    "Make Listicles from Compilation Videos",
    "Repurpose Live Chats into Articles",
    "Turn Workshops into Paid Content",
    "Create Social Proof Videos",
    "Repurpose Outtakes for Blooper Reels",
    "Turn Walkthroughs into Help Docs",
    "Make Mashups from Different Videos",
    "Repurpose Testimonials for Landing Pages",
    "Maximize ROI with Video Repurposing",
    "The Ultimate Video Recycling Guide",
    "How to Batch Produce Content",
    "Turn 1 Video into 10 Pieces of Content",
    "Video Repurposing Workflow Tips",
    "Automating Your Content Repurposing",
    "Best Tools for Content Repurposing",
    "Scaling Content with Video Downloads",
    "Repurposing Strategy for Influencers",
    "Corporate Video Repurposing Playbook",
    "Repurposing Educational Video Content",
    "Monetizing Repurposed Video Clips",
    "Repurposing Videos for SEO Growth",
    "Cross-Platform Video Distribution",
    "Repurposing Strategy for Small Businesses",
    "Creating a Content Waterfall",
    "The GaryVee Content Model Explained",
    "Repurposing Live Events Effectively",
    "Repurposing for B2B Marketing",
    "Repurposing for E-commerce Brands",
    "Repurposing Real Estate Tour Videos",
    "Repurposing Fitness Class Videos",
    "Repurposing Cooking Show Clips",
    "Repurposing Travel Vlog Footage",
    "Repurposing Music Performance Videos",
    "Repurposing Comedy Standup Sets",
    "Repurposing Tech Review Videos",
    "Repurposing Beauty Tutorial Clips",
    "Repurposing Gaming Montage Videos",
    "Repurposing Finance Tip Videos",
    "Repurposing DIY Craft Tutorials",
    "Repurposing Pet Training Videos",
    "Repurposing Automotive Repair Videos",
    "Repurposing Language Learning Clips",
    "Repurposing Gardening Tip Videos",
    "Repurposing Art Timelapse Videos",
    "Repurposing Yoga Routine Clips",
    "Repurposing Motivational Speeches",
    "Repurposing Political Commentary",
    "Repurposing News Recap Videos",
    "Repurposing Sports Analysis Clips",
    "Repurposing Movie Review Videos",
    "Repurposing Book Summary Videos",
    "Repurposing Magic Trick Reveals",
    "Repurposing ASMR Trigger Videos",
    "Repurposing Science Experiment Clips",
    "Repurposing Historical Fact Videos",
    "Repurposing True Crime Stories",
    "Repurposing Paranormal Investigation Videos",
    "Repurposing Conspiracy Theory Explanations",
    "Repurposing Tarot Card Readings",
    "Repurposing Astrology Forecast Videos",
    "Repurposing Productivity Hack Clips",
    "Repurposing Minimalist Lifestyle Tips",
    "Repurposing Sustainable Living Guides",
    "Repurposing Vegan Recipe Videos",
    "Repurposing Keto Diet Meal Plans",
    "Repurposing Intermittent Fasting Tips",
    "Repurposing Biohacking Strategy Videos",
    "Repurposing Nootropic Review Clips",
    "Repurposing Cryptocurrency Analysis",
    "Repurposing NFT Project Breakdowns",
    "Repurposing Stock Market Updates",
    "Repurposing Real Estate Investing Tips",
    "Repurposing Personal Finance Advice",
    "Repurposing Frugal Living Hacks",
    "Repurposing Couponing Strategy Videos",
    "Repurposing Side Hustle Ideas",
    "Repurposing Passive Income Guides",
    "Repurposing Dropshipping Tutorials",
    "Repurposing Amazon FBA Strategies",
    "Repurposing Affiliate Marketing Tips",
    "Repurposing SEO Tutorial Videos",
    "Repurposing Facebook Ads Guides",
    "Repurposing Google Ads Strategies",
    "Repurposing Email Marketing Tips",
    "Repurposing Copywriting Masterclasses",
    "Repurposing Web Design Tutorials",
    "Repurposing Graphic Design Tips",
    "Repurposing UI/UX Principle Videos",
    "Repurposing Programming Tutorials",
    "Repurposing Python Coding Guides",
    "Repurposing JavaScript Framework Lessons",
    "Repurposing React Development Tips",
    "Repurposing Node.js Backend Guides",
    "Repurposing SQL Database Tutorials",
    "Repurposing Cybersecurity Awareness Clips",
    "Repurposing Ethical Hacking Lessons",
    "Repurposing Cloud Computing Basics",
    "Repurposing AWS Certification Guides",
    "Repurposing Azure Deployment Tutorials",
    "Repurposing Docker Container Guides",
    "Repurposing Kubernetes Orchestration Lessons",
    "Repurposing Linux Command Tutorials",
    "Repurposing Windows Server Guides",
    "Repurposing MacOS Productivity Tips",
    "Repurposing iOS App Development",
    "Repurposing Android Studio Tutorials",
    "Repurposing Game Development Guides",
    "Repurposing Unity Engine Lessons",
    "Repurposing Unreal Engine Tutorials",
    "Repurposing Blender 3D Modeling",
    "Repurposing Maya Animation Guides",
    "Repurposing ZBrush Sculpting Tips",
    "Repurposing Adobe Premiere Pro Tricks",
    "Repurposing After Effects Compositing",
    "Repurposing Final Cut Pro Workflows",
    "Repurposing DaVinci Resolve Color Grading",
    "Repurposing Logic Pro Music Production",
    "Repurposing Ableton Live Beatmaking",
    "Repurposing FL Studio Tutorials",
    "Repurposing Pro Tools Mixing Guides",
    "Repurposing Photography Composition Tips",
    "Repurposing Lightroom Preset Guides",
    "Repurposing Photoshop Retouching Tricks",
    "Repurposing Illustrator Vector Tutorials",
    "Repurposing InDesign Layout Guides",
    "Repurposing Figma Prototyping Lessons",
    "Repurposing Sketch UI Design Tips",
    "Repurposing Canva Design Hacks",
    "Repurposing Notion Template Builds",
    "Repurposing Airtable Database Setups",
    "Repurposing Zapier Automation Guides",
    "Repurposing Make (Integromat) Scenarios",
    "Repurposing Monday.com Workflows",
    "Repurposing Asana Project Management",
    "Repurposing Trello Board Setups",
    "Repurposing Jira Agile Tracking",
    "Repurposing Slack Communication Tips",
    "Repurposing Microsoft Teams Guides",
    "Repurposing Zoom Meeting Hacks",
    "Repurposing Google Workspace Tips",
    "Repurposing Office 365 Tutorials",
    "Repurposing Excel Pivot Table Guides",
    "Repurposing Word Formatting Tricks",
    "Repurposing PowerPoint Presentation Tips",
    "Repurposing Salesforce CRM Tutorials",
    "Repurposing HubSpot Inbound Marketing",
    "Repurposing Mailchimp Campaign Guides",
    "Repurposing Klaviyo E-commerce Tips",
    "Repurposing Shopify Store Setup Guides",
    "Repurposing WooCommerce Plugin Tips",
    "Repurposing WordPress Security Tricks",
    "Repurposing Elementor Page Building",
    "Repurposing Divi Theme Customization",
    "Repurposing Wix Website Design",
    "Repurposing Squarespace Portfolio Setups",
    "Repurposing Webflow Interaction Guides",
    "Repurposing Framer Prototyping Tips",
    "Repurposing Ghost Blogging Platform Guides"
  ],
  "Video SEO": [
    "How Video Downloads Boost SEO",
    "Optimizing Downloaded Videos for Web",
    "Best Video Formats for Fast Loading",
    "Writing SEO-Friendly Video Titles",
    "Crafting High-Converting Video Thumbnails",
    "Using Video Metadata for Ranking",
    "How Transcriptions Improve Video SEO",
    "Adding Subtitles to Downloaded Videos",
    "Creating SRT Files for Video Content",
    "Optimizing Video Tags on YouTube",
    "Leveraging Video Descriptions for Search",
    "Embedding Videos for Page SEO",
    "Impact of Video on Bounce Rate",
    "Schema Markup for Video Content",
    "Hosting vs. Embedding Video Impact",
    "Improving Video Engagement Metrics",
    "A/B Testing Video Thumbnails",
    "Optimizing Videos for Mobile Viewing",
    "Compressing Video Files for Speed",
    "Best Video Compression Tools",
    "SEO Benefits of YouTube Shorts",
    "Ranking Videos in Google Search",
    "Video SEO Auditing Your Website",
    "Keyword Research for Video Content",
    "Utilizing Long-Tail Video Keywords",
    "Analyzing Competitor Video SEO",
    "Understanding YouTube Algorithm Updates",
    "Maximizing TikTok SEO Visibility",
    "Instagram Reels Algorithm Secrets",
    "Optimizing Video for Voice Search",
    "Local SEO Strategies with Video",
    "Building Backlinks with Video Content",
    "Guest Posting with Embedded Videos",
    "Video Sitemaps for Better Crawling",
    "Rich Snippets for Video Results",
    "Increasing Video Click-Through Rates",
    "Optimizing Video End Screens",
    "Effective Use of Video Cards",
    "Crafting Video Playlists for SEO",
    "Driving Traffic from YouTube to Blog",
    "Tracking Video Analytics in GA4",
    "Understanding Video Audience Retention",
    "Improving Watch Time Metrics",
    "Video Marketing KPIs to Track",
    "Using Heatmaps for Video Engagement",
    "Optimizing Video Landing Pages",
    "SEO Best Practices for Webinars",
    "Optimizing Product Demonstration Videos",
    "Customer Testimonial Video SEO",
    "Corporate Explainer Video Optimization",
    "Boosting E-commerce Conversions with Video",
    "Integrating Video into Content Strategy",
    "Repurposing Blog Content into Video",
    "Aligning Video SEO with Brand Voice",
    "International Video SEO Strategies",
    "Translating Video Content for Global Reach",
    "Multi-Language Subtitle SEO Benefits",
    "Geotargeting Video Ads for Local SEO",
    "Seasonal Video Content Optimization",
    "Evergreen Video SEO Tactics",
    "Trending Keyword Integration in Video",
    "Leveraging Google Trends for Videos",
    "YouTube Autocomplete for Keyword Ideas",
    "Optimizing Live Streams for Replay Value",
    "Pre-Premiere SEO for Video Launches",
    "Post-Launch Video SEO Checklist",
    "Reviving Old Videos with SEO Tweaks",
    "Deleting Underperforming Video Content",
    "Channel Authority and Video Ranking",
    "Building Subscriber Base for Better SEO",
    "Cross-Promoting Videos for Backlinks",
    "Collaborating for Shared Video SEO",
    "Influencer Partnerships for Video Reach",
    "User-Generated Video Content SEO",
    "Encouraging Video Comments for Engagement",
    "Responding to Comments for Algorithm Boost",
    "Pinned Comments SEO Strategy",
    "Community Tab Optimization on YouTube",
    "Optimizing Channel \"About\" Section",
    "Creating a Channel Trailer for Conversions",
    "Watermarking Videos for Brand Search",
    "Custom Video URLs and Branding",
    "Aligning Thumbnail Text with Keywords",
    "Color Psychology in Video Thumbnails",
    "Human Faces in Thumbnails and CTR",
    "A/B Testing Video Titles for SEO",
    "Emojis in Video Titles: SEO Impact",
    "Using Brackets in Titles for Clicks",
    "Question-Based Titles for Voice Search",
    "How-To vs. Tutorial SEO Differences",
    "Review Video Optimization Strategies",
    "Comparison Video SEO (X vs Y)",
    "Unboxing Video SEO Best Practices",
    "Vlogging SEO Tips for Creators",
    "Gaming Channel SEO Strategies",
    "Tech Channel Optimization Tactics",
    "Beauty Guru Video SEO Secrets",
    "Fitness Instructor Video Ranking",
    "Finance Channel YouTube Algorithm",
    "Real Estate Video SEO Playbook",
    "Music Channel Optimization Guide",
    "Comedy Sketch Video Discoverability",
    "Educational Channel SEO Framework",
    "Children's Content YouTube SEO",
    "ASMR Channel Growth Strategies",
    "True Crime Video Algorithm Optimization",
    "News Channel Fast-Ranking Tactics",
    "Sports Highlight SEO Optimization",
    "Political Commentary Algorithm Tips",
    "Reaction Video SEO Vulnerabilities",
    "Fair Use and Video Takedowns",
    "Avoiding Copyright Strikes for SEO",
    "Music Licensing for Video Ranking",
    "Creative Commons Video Optimization",
    "Public Domain Footage Use",
    "Stock Video Impact on Algorithm",
    "Unique Editing Styles and Watch Time",
    "Jump Cuts vs. Continuous Takes SEO",
    "B-Roll Importance for Retention",
    "Background Music Impact on Engagement",
    "Sound Effects and Audience Retention",
    "Intro Length and Drop-off Rates",
    "The First 5 Seconds Video Hook",
    "Outro Strategies for Binge-Watching",
    "Call to Action Placement for SEO",
    "Subscribe Buttons vs. Bell Notifications",
    "Driving Traffic to Affiliate Links",
    "Patreon Link Optimization in Video",
    "Merchandise Shelf SEO Integration",
    "YouTube Shorts Feed Algorithm",
    "TikTok FYP Algorithm Explained",
    "Instagram Explore Page Video Ranking",
    "Facebook Watch Algorithm Factors",
    "LinkedIn Video Feed Optimization",
    "Twitter Video Engagement Metrics",
    "Pinterest Idea Pin Optimization",
    "Snapchat Discover Algorithm",
    "Twitch VOD Discoverability",
    "Vimeo Staff Pick Optimization",
    "Dailymotion SEO Strategies",
    "Rumble Algorithm and Discoverability",
    "Bilibili Ranking Factors",
    "Optimizing Videos for Smart TVs",
    "Roku Channel Video SEO",
    "Apple TV App Video Discoverability",
    "Amazon Fire TV Content Ranking",
    "Optimizing VR Video Content",
    "360-Degree Video SEO Tactics",
    "AR Video Engagement Metrics",
    "Interactive Video SEO Benefits",
    "Shoppable Video Conversion Rates",
    "Livestream E-commerce SEO",
    "Webinar Registration Page Optimization",
    "Gated Video Content Strategies",
    "Lead Generation with Video Downloads",
    "Email Capture via Video Gates",
    "Video Retargeting Audience Building",
    "Custom Audiences from Video Views",
    "Lookalike Audiences via Video Engagement",
    "Optimizing YouTube Ads for Views",
    "TrueView Video Discovery Ads",
    "Bumper Ads vs. Skippable Ads",
    "Outstream Video Ad Placement",
    "Masthead Ads YouTube Strategy",
    "TikTok Spark Ads Optimization",
    "Instagram Reel Ads Best Practices",
    "Facebook In-Stream Video Ads",
    "LinkedIn Video Ad Targeting",
    "Twitter Amplify Pre-Roll Ads",
    "Pinterest Video Ad Conversion",
    "Snapchat Commercial Ad SEO",
    "Hulu Ad Manager Campaign Optimization",
    "Connected TV (CTV) Ad Targeting",
    "OTT Video Advertising Strategies",
    "Programmatic Video Ad Buying",
    "Video Ad Viewability Metrics",
    "VAST and VPAID Tag Optimization",
    "Header Bidding for Video Inventory",
    "Maximizing Video CPMs for Publishers",
    "Minimizing Ad Block Impact on Video",
    "Server-Side Ad Insertion (SSAI)",
    "Client-Side Ad Insertion (CSAI)",
    "Native Video Ad Optimization",
    "Rewarded Video Ad Engagement",
    "Playable Ads Conversion Rates",
    "Interstitial Video Ad Best Practices",
    "Banner Ads vs. Video Ads ROI",
    "Ad Fatigue in Video Campaigns",
    "Frequency Capping Video Ads",
    "Sequencing Video Ad Messages",
    "Personalization in Video Advertising",
    "Dynamic Creative Optimization (DCO)",
    "AI in Video Ad Targeting",
    "Contextual Video Targeting Strategies",
    "Behavioral Targeting with Video Data",
    "Demographic Targeting for Video",
    "Psychographic Targeting in Video Ads",
    "First-Party Data for Video SEO",
    "Third-Party Cookie Phaseout Impact",
    "Privacy-First Video Marketing"
  ],
  "Tech Fixes": [
    "Downloader Not Working: Quick Fixes",
    "How to Fix \"URL Not Supported\" Error",
    "Resolving Audio/Video Sync Issues",
    "Why is My Download So Slow?",
    "Fixing \"File Corrupted\" Download Errors",
    "How to Bypass Geo-Blocked Videos",
    "Resolving \"Video Not Available\" Errors",
    "Fixing 4K Video Download Failures",
    "How to Download Age-Restricted Videos",
    "Fixing Subtitle Download Errors",
    "Resolving MP4 to MP3 Conversion Bugs",
    "Why Does My Video Have No Sound?",
    "Fixing \"Network Error\" During Download",
    "How to Resume Broken Downloads",
    "Resolving Browser Extension Conflicts",
    "Fixing Video Downloader App Crashes",
    "Why is the Downloaded Quality Low?",
    "Fixing \"Access Denied\" Server Errors",
    "Troubleshooting Batch Download Failures",
    "Resolving Antivirus Blocking Downloads",
    "How to Clear Browser Cache for Downloads",
    "Fixing \"Insufficient Disk Space\" Errors",
    "Resolving Mobile Downloader App Bugs",
    "Fixing Background Download Interruptions",
    "How to Update Your Video Downloader",
    "Troubleshooting Private Video Access",
    "Fixing \"Invalid Link\" Error Messages",
    "Resolving Captcha Loops During Download",
    "Fixing API Rate Limit Errors",
    "Troubleshooting VPN Video Download Blocks",
    "Fixing \"Video Deleted\" Download Attempts",
    "Resolving DRM Protection Errors",
    "Troubleshooting Live Stream Captures",
    "Fixing Fragmented Video File Merging",
    "Resolving M3U8 Playlist Download Errors",
    "Fixing TS File Conversion Issues",
    "Troubleshooting HLS Stream Downloads",
    "Resolving DASH Video Capture Errors",
    "Fixing WebM Compatibility Issues",
    "Troubleshooting HEVC/H.265 Playback",
    "Resolving AV1 Codec Download Errors",
    "Fixing ProRes Video File Handling",
    "Troubleshooting MKV Subtitle Extraction",
    "Resolving FLV Legacy Format Issues",
    "Fixing MOV to MP4 Conversion Bugs",
    "Troubleshooting WMV File Playback",
    "Resolving AVI Sync Problem Fixes",
    "Fixing OGG Audio Extraction Errors",
    "Troubleshooting WAV File Export Issues",
    "Resolving FLAC High-Res Audio Drops",
    "Fixing AAC Audio Bitrate Errors",
    "Troubleshooting M4A File Compatibility",
    "Resolving Metadata Loss After Download",
    "Fixing Incorrect Aspect Ratio Downloads",
    "Troubleshooting Dropped Frames Issue",
    "Resolving Variable Frame Rate (VFR) Sync",
    "Fixing Constant Frame Rate (CFR) Conversion",
    "Troubleshooting 60fps Video Downgrades",
    "Resolving 120fps/144fps Capture Limitations",
    "Fixing HDR to SDR Tonemapping Errors",
    "Troubleshooting Dolby Vision Playback",
    "Resolving HDR10+ Color Space Issues",
    "Fixing 10-bit Color Banding Artifacts",
    "Troubleshooting 4:4:4 Chroma Subsampling",
    "Resolving Rec.709/Rec.2020 Mismatches",
    "Fixing LUT Application on Downloaded Video",
    "Troubleshooting Interlaced Video Deinterlacing",
    "Resolving Telecine/Inverse Telecine Bugs",
    "Fixing Mac Video Downloader Compatibility",
    "Troubleshooting Windows 11 Downloader Issues",
    "Resolving Linux CLI Downloader Errors",
    "Fixing Android APK Parsing Errors",
    "Troubleshooting iOS Shortcut Failures",
    "Resolving Chrome Extension Blockages",
    "Fixing Firefox Add-on Memory Leaks",
    "Troubleshooting Safari Extension Restrictions",
    "Resolving Edge Browser Download Blocks",
    "Fixing Opera VPN Video Streaming",
    "Troubleshooting Brave Shields Blocking Scripts",
    "Resolving Vivaldi Browser Compatibility",
    "Fixing Android TV Downloader Limitations",
    "Troubleshooting Apple TV AirPlay Drops",
    "Resolving Chromecast Video Casting Errors",
    "Fixing Roku USB Playback Formats",
    "Troubleshooting Firestick Downloader Storage",
    "Resolving Kodi Add-on Source Failures",
    "Fixing Plex Media Server Recognition",
    "Troubleshooting Jellyfin Metadata Scraping",
    "Resolving Emby Server Transcoding Errors",
    "Fixing NAS Storage Video Streaming",
    "Troubleshooting Synology Video Station Bugs",
    "Resolving QNAP Video Playback Issues",
    "Fixing Docker Container Downloader Setups",
    "Troubleshooting Raspberry Pi Media Centers",
    "Resolving Wi-Fi Bandwidth Throttling",
    "Fixing Ethernet Connection Dropouts",
    "Troubleshooting ISP Traffic Shaping",
    "Resolving CDN Node Timeout Errors",
    "Fixing DNS Resolution for Video Sites",
    "Troubleshooting IPv6 Video Routing",
    "Resolving NAT Type Strict Blocks",
    "Fixing Port Forwarding for P2P Video",
    "Troubleshooting BitTorrent Video Downloads",
    "Resolving Magnet Link Application Handlers",
    "Fixing Usenet Video File Assembly",
    "Troubleshooting RAR Archive Passwords",
    "Resolving ZIP File Extraction Corruption",
    "Fixing 7z Multi-Part Archive Errors",
    "Troubleshooting Tarball Video Extractions",
    "Resolving MD5 Hash Mismatch Errors",
    "Fixing SHA-256 Checksum Failures",
    "Troubleshooting Parity File Repairs",
    "Resolving FTP Video Transfer Timeouts",
    "Fixing SFTP Key Authentication Errors",
    "Troubleshooting WebDAV Mount Disconnects",
    "Resolving SMB Share Permission Denials",
    "Fixing NFS Mount Stale File Handles",
    "Troubleshooting USB Flash Drive Formats",
    "Resolving External HDD Spin-Down Freezes",
    "Fixing SSD Wear Leveling Impact",
    "Troubleshooting SD Card Write Protection",
    "Resolving MicroSD Class Speed Bottlenecks",
    "Fixing Cloud Storage Sync Conflicts",
    "Troubleshooting Google Drive Quota Limits",
    "Resolving Dropbox File Size Restrictions",
    "Fixing OneDrive Sync Stuck on Processing",
    "Troubleshooting iCloud Video Upload Stalls",
    "Resolving Mega.nz Bandwidth Limits",
    "Fixing Box.com Enterprise Restrictions",
    "Troubleshooting MediaFire Captcha Loops",
    "Resolving Zippyshare Dead Link Errors",
    "Fixing Rapidgator Premium Account Blocks",
    "Troubleshooting Uploaded.net Slow Speeds",
    "Resolving 1fichier Waiting Time Bypasses",
    "Fixing Uptobox Geo-Restrictions",
    "Troubleshooting Video Hosting DMCA Takedowns",
    "Resolving Content ID Claim Disputes",
    "Fixing Fair Use Video Editing Tricks",
    "Troubleshooting Copyright Strike Recovery",
    "Resolving Channel Demonetization Appeals",
    "Fixing AdSense Payment Hold Issues",
    "Troubleshooting MCN Network Release Forms",
    "Resolving Sponsorship Integration Guidelines",
    "Fixing Affiliate Link Shadowbans",
    "Troubleshooting Merchandise Store Integrations",
    "Resolving Patreon API Disconnects",
    "Fixing Discord Bot Video Embedding",
    "Troubleshooting Twitch Stream Key Resets",
    "Resolving YouTube Studio Processing Stuck",
    "Fixing Facebook Creator Studio Bugs",
    "Troubleshooting Instagram Graph API Errors",
    "Resolving TikTok Developer Token Expirations",
    "Fixing Twitter Media Studio Upload Failures",
    "Troubleshooting LinkedIn Video Processing Error",
    "Resolving Pinterest Video Pin Rejections",
    "Fixing Snapchat Lens Studio Video Limits",
    "Troubleshooting Vimeo Pro Storage Quotas",
    "Resolving Wistia Player Customization Bugs",
    "Fixing Brightcove Analytics Discrepancies",
    "Troubleshooting Kaltura Video Integration",
    "Resolving Panopto Blackboard Sync Issues",
    "Moodle Video File Size Limits",
    "Canvas Video Submission Errors",
    "Resolving Google Classroom Drive Links",
    "Fixing Microsoft Stream Organization Access",
    "Troubleshooting Slack Video Call Drops",
    "Resolving Zoom Screen Share Black Screens",
    "Fixing Webex Recording Audio Echoes",
    "Troubleshooting Google Meet Resolution Drops",
    "Resolving Skype Camera Not Detected Errors",
    "Fixing OBS Studio Encoding Overload",
    "Troubleshooting Streamlabs Dropped Frames",
    "Resolving XSplit Virtual Camera Glitches",
    "Fixing vMix NDI Source Latency",
    "Troubleshooting Wirecast Audio Desync",
    "Resolving Elgato Capture Card Screen Tearing",
    "Fixing AverMedia HDCP Protection Blocks",
    "Troubleshooting Blackmagic ATEM Switcher Bugs",
    "Resolving DSLR HDMI Output Blank Screens",
    "Fixing Mirrorless Camera Overheating",
    "Troubleshooting Webcam Auto-Focus Hunting",
    "Resolving Ring Light Flicker in Video",
    "Fixing Green Screen Chroma Key Spill",
    "Troubleshooting Microphone Background Noise",
    "Resolving Audio Interface Phantom Power Hum",
    "Fixing USB Mic Driver Conflicts",
    "Troubleshooting Lav Mic Static Crackle",
    "Resolving Shotgun Mic Wind Interference",
    "Fixing Room Reverb Audio Echo",
    "Troubleshooting Dual Monitor Setup Lag",
    "Resolving GPU Hardware Acceleration Crashes",
    "Fixing CPU Thermal Throttling Spikes",
    "Troubleshooting RAM Allocation Errors",
    "Resolving Motherboard PCIe Lane Bottlenecks",
    "Fixing Power Supply Surge Shutdowns",
    "Troubleshooting Windows Blue Screen (BSOD)",
    "Resolving Kernel Panic on MacOS",
    "Fixing Linux X11/Wayland Display Glitches",
    "Troubleshooting UEFI BIOS Update Bricks",
    "Resolving Firmware Over-The-Air (OTA) Fails"
  ],
  "Video Editing": [
    "Best Video Editing Software for Beginners",
    "How to Trim Downloaded Videos Easily",
    "Merging Multiple Video Clips Together",
    "Adding Watermarks to Your Videos",
    "Removing Background Noise from Video Audio",
    "How to Extract MP3 from MP4 Files",
    "Changing Video Aspect Ratios for Social",
    "Converting Horizontal Video to Vertical",
    "Best Video Compression Settings",
    "Adding Text Overlays to Downloaded Video",
    "How to Blur Faces in Video Editing",
    "Creating Smooth Video Transitions",
    "Color Correction Basics for Video",
    "How to Speed Up or Slow Down Video",
    "Creating Timelapse Videos from Downloads",
    "How to Make a GIF from a Video Clip",
    "Adding Background Music to Videos",
    "Syncing Audio and Video Perfectly",
    "How to Export Videos in 4K Quality",
    "Best Export Settings for YouTube",
    "TikTok Video Formatting Guidelines",
    "Instagram Reels Dimensions & Specs",
    "Video Editing Keyboard Shortcuts",
    "Using LUTS for Cinematic Video Looks",
    "How to Edit Green Screen Footage",
    "Creating Custom Video Intros/Outros",
    "Best Free Fonts for Video Subtitles",
    "How to Auto-Generate Captions",
    "Hardcoding Subtitles into MP4 Files",
    "Editing Videos on iPhone vs Android",
    "CapCut Editing Tutorial for Beginners",
    "Adobe Premiere Pro Essential Tips",
    "Final Cut Pro X Workflow Hacks",
    "DaVinci Resolve Color Grading Guide",
    "iMovie Tips for Quick Video Edits",
    "Filmora Wondershare Feature Breakdown",
    "Sony Vegas Pro Interface Guide",
    "Canva Video Editing Features",
    "InVideo vs Promo: Which is Better?",
    "Browser-Based Video Editors Reviewed",
    "How to Resize Video File Size",
    "Removing Black Bars from Videos",
    "Fixing Shaky Video Footage (Stabilization)",
    "How to Reverse a Video Clip",
    "Adding Voiceovers to Downloaded Videos",
    "Creating Picture-in-Picture (PiP) Effects",
    "How to Censor Audio (Bleeps)",
    "Audio Ducking for Background Music",
    "Normalizing Video Audio Levels",
    "How to Change Video Frame Rates",
    "Upscaling 1080p Video to 4K AI",
    "Deinterlacing Old Video Footage",
    "Removing Logos from Downloaded Videos",
    "Adding Interactive Elements to Video",
    "360-Degree Video Editing Basics",
    "Editing Drone Footage for Smoothness",
    "GoPro Video Editing Software Tips",
    "Creating Split-Screen Video Layouts",
    "Best Stock Video Sites for B-Roll",
    "Where to Find Royalty-Free Audio",
    "Adding Sound Effects (SFX) to Video",
    "Using Video Templates to Save Time",
    "Creating Engaging Video Hooks",
    "How to Cut on the Beat in Editing",
    "Jump Cuts: When and How to Use Them",
    "J-Cuts and L-Cuts Explained",
    "Crossfade vs Dip to Black",
    "Understanding Video Bitrates",
    "CBR vs VBR Encoding Differences",
    "H.264 vs H.265 Codec Comparison",
    "ProRes vs DNxHD Formats",
    "Understanding Color Spaces (Rec.709)",
    "8-Bit vs 10-Bit Color Depth",
    "How to Edit HDR Video Content",
    "Best Laptops for Video Editing 2026",
    "Desktop Build Guide for Video Editing",
    "Using an iPad Pro for Video Editing",
    "External SSDs for Video Storage",
    "NAS Setup for Video Archiving",
    "Cloud Storage Solutions for Video Files",
    "Proxy Editing for Slow Computers",
    "Optimizing Media Cache for Performance",
    "Batch Processing Video Files",
    "Command Line Video Editing with FFmpeg",
    "Automating Edits with Python Scripts",
    "Best Open Source Video Editors",
    "Kdenlive vs Shotcut Comparison",
    "OpenShot Video Editor Review",
    "Lightworks Free vs Pro Version",
    "HitFilm Express Visual Effects",
    "Blender for Video Sequence Editing",
    "Natron for Node-Based Compositing",
    "After Effects Motion Graphics Basics",
    "Creating Animated Lower Thirds",
    "Tracking Text to Moving Objects",
    "Rotoscoping Explained for Beginners",
    "Adding Lens Flares and Light Leaks",
    "Glitch Effects for Edgy Videos",
    "VHS Retro Video Filter Tutorials",
    "Film Grain Effect Settings",
    "Stop Motion Animation Editing",
    "Cinemagraph Creation from Video",
    "Keyframing Animation Basics",
    "Masking Techniques in Video Editing",
    "Multi-Camera Editing Workflow",
    "Syncing PluralEyes Audio Automatically",
    "Understanding Timecode in Video",
    "SMPTE Color Bars and Calibration",
    "Audio EQ Sweeping for Vocals",
    "Adding Compression to Voiceovers",
    "De-Esser Settings for Microphones",
    "Noise Gate for Clean Audio",
    "Reverb and Delay Video Effects",
    "Mastering Video Audio Standards",
    "LUFS Loudness Targets for Platforms",
    "Exporting Video with Transparent Background",
    "WebM Alpha Channel Export Guide",
    "Creating Lottie Animations",
    "SVG Animation vs Video Files",
    "Best Video Formats for HTML5",
    "CSS Video Styling Tricks",
    "Video Backgrounds in Web Design",
    "Lazy Loading Videos on WordPress",
    "Video Plugins for Elementor Pages",
    "Creating a Video Portfolio Website",
    "Showreel Editing Tips for Creators",
    "Trailer Editing Pacing Guidelines",
    "Documentary Storyboarding and Editing",
    "Music Video Editing Techniques",
    "Wedding Video Color Grading Styles",
    "Real Estate Video Drone Edits",
    "Corporate Interview Editing Setup",
    "Vlogging Jump Cut Masterclass",
    "Gaming Montage Syncing Tricks",
    "Sports Highlight Reel Pacing",
    "Educational Video On-Screen Graphics",
    "Whiteboard Animation Video Software",
    "Explainer Video Vector Animation",
    "Typography Video Design Principles",
    "Kinetic Typography Premiere Pro Guide",
    "Video Aspect Ratio Cheat Sheet",
    "Safe Zones for Mobile Video Platforms",
    "Designing Thumbnails While Editing",
    "Storyboarding Your Edits Beforehand",
    "Organizing Your Project Bins",
    "Naming Conventions for Video Files",
    "Archiving Completed Video Projects",
    "Collaborative Video Editing Tools",
    "Frame.io Review and Workflow",
    "Wipster Video Feedback Features",
    "Post-Production Timeline Management",
    "Hiring a Freelance Video Editor",
    "Pricing Your Video Editing Services",
    "Creating an Editing Contract",
    "Dealing with Client Revisions",
    "Video Copyright Release Forms",
    "AI Video Editing Revolution",
    "Descript Audio/Text Video Editing",
    "RunwayML AI Magic Tools",
    "Midjourney AI Assets in Video",
    "ChatGPT Scripting for Video Edits",
    "ElevenLabs AI Voiceovers in Edits",
    "Synthesia AI Avatar Video Creation",
    "Deepfake Technology Ethics in Editing",
    "Neural Filters in Video Software",
    "AI Auto-Framing for Social Media",
    "Auto-Podcasting Camera Switching AI",
    "Best Color Grading Control Panels",
    "Loupedeck CT for Video Editing",
    "Stream Deck Macros for Premiere",
    "Ergonomic Mouse for Editing (MX Master)",
    "Best Monitors for Accurate Color Grading",
    "Calibrating Display for Video Editing",
    "Bias Lighting for Editing Studios",
    "Studio Monitor Speakers for Video Audio",
    "Acoustic Treatment for Editing Rooms",
    "Standing Desks for Video Editors",
    "Preventing Eye Strain During Long Edits",
    "Mental Fatigue and Creative Editing",
    "The Psychology of Cutting on Movement",
    "Kuleshov Effect in Modern Editing",
    "Eisenstein's Montage Theory Explained",
    "Walter Murch's Rule of Six",
    "Editing for Emotional Impact",
    "Pacing and Rhythm in Storytelling",
    "The Invisible Cut Technique",
    "Match Cuts for Seamless Transitions",
    "Smash Cuts to Shift Tone",
    "Parallel Editing/Cross-Cutting Guide",
    "The Action Axis (180-Degree Rule)",
    "Breaking the 180-Degree Rule Deliberately",
    "Shot/Reverse Shot Interview Editing",
    "Establishing Shots vs Detail Shots",
    "POV Shot Editing Implementation",
    "Dutch Angle Editing Psychology",
    "Zoom vs Dolly Shot Dynamics",
    "Rack Focus Execution in Post",
    "Lens Distortion Correction Tricks",
    "Chromatic Aberration Adding/Removing",
    "The Future of Cloud-Based Video Editing"
  ]
};

async function main() {
  console.log('Starting Auto-Blog Database Seeding...');

  // Fetch the 5 categories we created earlier
  const categories = await prisma.category.findMany();
  
  if (categories.length === 0) {
    console.error('No categories found! Please run the first cleanup script to create categories.');
    process.exit(1);
  }

  // Map category names to their IDs
  const categoryMap = {};
  categories.forEach(cat => {
    categoryMap[cat.name] = cat.id;
  });

  let totalInserted = 0;

  for (const [categoryName, topics] of Object.entries(topicsData)) {
    const categoryId = categoryMap[categoryName];
    
    if (!categoryId) {
      console.warn(`Category "${categoryName}" not found in DB! Skipping its topics.`);
      continue;
    }

    // Insert topics for this category
    const topicRecords = topics.map(title => ({
      title: title,
      categoryId: categoryId,
      status: 'pending'
    }));

    // Bulk insert using createMany
    const result = await prisma.autoBlogTopic.createMany({
      data: topicRecords
    });

    console.log(`Inserted ${result.count} topics into "${categoryName}".`);
    totalInserted += result.count;
  }

  console.log(`\nSuccess! Seeded a total of ${totalInserted} Auto-Blog Topics.`);
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
